/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mavn.simulation.view.controlBar;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import simulyn.ui.components.ControlButton;

/**
 *
 * @author Kaleb
 */
public class SubControlBar extends javax.swing.JPanel
{

    private ActionListener runSimulationAction;
    private JButton runSimulationButton;
    private JButton resetSimulationButton;

    /**
     * Creates new form SubControlBar
     */
    public SubControlBar(ActionListener runSimulationAction)
    {

        this.runSimulationAction = runSimulationAction;

        initComponents();
        initButtons();
        initActions();

        viewSubControlBar.setLayout(new BoxLayout(viewSubControlBar, BoxLayout.LINE_AXIS));

    }

    public JButton getResetSimulationButton()
    {
        return resetSimulationButton;
    }

    public JButton getRunSimulationButton()
    {
        return runSimulationButton;
    }

    private void initActions()
    {
        // Run Simulation Action
        runSimulationButton.addActionListener(this.runSimulationAction);
        runSimulationButton.setActionCommand("runSimulationAction");
        resetSimulationButton.addActionListener(this.runSimulationAction);
        resetSimulationButton.setActionCommand("resetSimulationAction");
    }

    private void initButtons()
    {
        runSimulationButton = new ControlButton(getIcon("/icons/runSimulation.png"));
        runSimulationButton.setText("Run Simulation");
        runSimulationButton.setFont(new Font("Roboto", Font.BOLD, 12));
        viewSubControlBar.add(runSimulationButton);

        resetSimulationButton = new ControlButton(getIcon("/icons/resetSimulation.png"));
        resetSimulationButton.setText("Reset Simulation");
        resetSimulationButton.setFont(new Font("Roboto", Font.BOLD, 12));
        viewSubControlBar.add(resetSimulationButton);
    }

    /**
     * Get an Image Icon from the path.
     *
     * @param iconPath the path of the desired image.
     * @return an Image Icon from the path.
     */
    public ImageIcon getIcon(String iconPath)
    {
        // Set Icon for button
        ImageIcon icon = createImageIcon(iconPath, "");
        Image img = icon.getImage();
        Image newimg = img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg, "");

        return newIcon;
    }

    /**
     * Returns an ImageIcon, or null if the path was invalid.
     */
    private ImageIcon createImageIcon(String path,
            String description)
    {
        java.net.URL imgURL = getClass().getResource(path);

        if (imgURL != null)
        {
            return new ImageIcon(imgURL, description);
        } else
        {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        viewSubControlBar = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(300, 69));

        viewSubControlBar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)), "Controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Cn", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N
        viewSubControlBar.setPreferredSize(new java.awt.Dimension(275, 69));
        viewSubControlBar.setRequestFocusEnabled(false);

        javax.swing.GroupLayout viewSubControlBarLayout = new javax.swing.GroupLayout(viewSubControlBar);
        viewSubControlBar.setLayout(viewSubControlBarLayout);
        viewSubControlBarLayout.setHorizontalGroup(
            viewSubControlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        viewSubControlBarLayout.setVerticalGroup(
            viewSubControlBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewSubControlBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewSubControlBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel viewSubControlBar;
    // End of variables declaration//GEN-END:variables
}
