package mavn.view.input;

import javax.swing.JButton;
import mavn.simModel.input.controller.ModelInputFileInterface;
import mavn.simModel.input.model.ModelInputInterface;
import spreadsheetTable.SimTable;
import util.components.BlinkerButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * inputPanel.java
 *
 * Created on Feb 23, 2012, 2:47:29 PM
 */
/**
 *
 * @author Kaleb
 */
public abstract class ModelInputPanelAbstract extends javax.swing.JPanel
{

    protected ModelInputFileInterface inputController;
    protected ModelInputInterface inputModel;
    protected ModelChangeEvent modelChanged;

    /** Creates new form inputPanel */
    public ModelInputPanelAbstract(ModelInputFileInterface inputController, ModelInputInterface inputModel, ModelChangeEvent modelChanged)
    {
        this.modelChanged = modelChanged;
        initComponents();
        this.inputController = inputController;
        this.inputModel = inputModel;
        this.addPropertyChangeListener(this.modelChanged);
    }

    public JButton getImportModelButton()
    {
        return importModelButton;
    }

    public JButton getSaveModelButton()
    {
        return saveModelButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        inputPanelHeaderLabel = new javax.swing.JLabel();
        importModelButton = new BlinkerButton("Import Matrix", "Blue");
        jSeparator3 = new javax.swing.JSeparator();
        inputPanelDescriptionLabel = new javax.swing.JLabel();
        saveModelButton = new BlinkerButton("Save Matrix", "Green");
        inputPane = new SimTable();
        setModelButton = new javax.swing.JButton();

        inputPanel.setPreferredSize(new java.awt.Dimension(650, 215));

        inputPanelHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        inputPanelHeaderLabel.setText("Input Panel");

        importModelButton.setText("Import Model");
        importModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importModelButtonActionPerformed(evt);
            }
        });

        inputPanelDescriptionLabel.setFont(new java.awt.Font("Tahoma", 3, 11));
        inputPanelDescriptionLabel.setText("Input Panel Description");

        saveModelButton.setText("Save Model");
        saveModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveModelButtonActionPerformed(evt);
            }
        });

        setModelButton.setText("Set Model");
        setModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setModelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createSequentialGroup()
                        .addComponent(importModelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveModelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setModelButton))
                    .addComponent(inputPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPanelHeaderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanelDescriptionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        inputPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {importModelButton, saveModelButton, setModelButton});

        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addComponent(inputPanelHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importModelButton)
                    .addComponent(saveModelButton)
                    .addComponent(setModelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanelDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPane, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importModelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_importModelButtonActionPerformed
    {//GEN-HEADEREND:event_importModelButtonActionPerformed
        inputController.importModelInput();
}//GEN-LAST:event_importModelButtonActionPerformed

    private void saveModelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveModelButtonActionPerformed
    {//GEN-HEADEREND:event_saveModelButtonActionPerformed
        inputController.exportModelInput();
}//GEN-LAST:event_saveModelButtonActionPerformed

    private void setModelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_setModelButtonActionPerformed
    {//GEN-HEADEREND:event_setModelButtonActionPerformed
        inputModel.setModelInput(((SimTable) inputPane).getModel());        
    }//GEN-LAST:event_setModelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton importModelButton;
    protected javax.swing.JScrollPane inputPane;
    private javax.swing.JPanel inputPanel;
    protected javax.swing.JLabel inputPanelDescriptionLabel;
    protected javax.swing.JLabel inputPanelHeaderLabel;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton saveModelButton;
    private javax.swing.JButton setModelButton;
    // End of variables declaration//GEN-END:variables
}
