/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulynDefaultNetworkRenderer.java
 *
 * Created on Mar 11, 2012, 9:19:31 AM
 */
package mavn.network.view;

import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Kaleb
 */
public class MavnNetworkRenderer extends javax.swing.JPanel implements JUNGPanelAdapterInterface
{

    private JUNGPanelAdapter networkView;
    private double[][] w2 = new double[0][0];
    private double[][] w1 = new double[0][0];
    private double[][] w0 = new double[0][0];

    /** Creates new form SimulynDefaultNetworkRenderer */
    public MavnNetworkRenderer()
    {
        initComponents();
        networkView = new JUNGPanelAdapter(w2, w1, w0);
        networkPane.setViewportView(networkView);
        networkPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    }

    @Override
    public void fireNodes(double[] result)
    {
        networkView.fireNodes(result);
    }

    @Override
    public void setNetwork(double[][] w2, double[][] w1, double[][] w0)
    {
        networkView = new JUNGPanelAdapter(w2, w1, w0);
        networkPane.setViewportView(networkView);
        networkPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkPane = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(networkPane, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(networkPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane networkPane;
    // End of variables declaration//GEN-END:variables
}
